ALTER TABLE students
  ADD COLUMN IF NOT EXISTS birth_date DATE NULL,
  ADD COLUMN IF NOT EXISTS guardian_name TEXT NULL,
  ADD COLUMN IF NOT EXISTS guardian_phone TEXT NULL,
  ADD COLUMN IF NOT EXISTS student_email TEXT NULL,
  ADD COLUMN IF NOT EXISTS notes TEXT NULL;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS full_name TEXT NULL,
  ADD COLUMN IF NOT EXISTS phone TEXT NULL;

CREATE INDEX IF NOT EXISTS idx_students_birth_date ON students (birth_date);
